In [1]:
print("Everything is perfect for starting the coding")

Everything is perfect for starting the coding

In [17]:
import pandas as pd

In [18]:
data=pd.read_csv("https://raw.githubusercontent.com/Ankit152/IMDB-sentiment-analysis/master/IMDB-Dataset.csv")

In [12]:
data.head()

                                              review sentiment
0  One of the other reviewers has mentioned that ...  positive
1  A wonderful little production. <br /><br />The...  positive
2  I thought this was a wonderful way to spend ti...  positive
3  Basically there's a family where a little boy ...  negative
4  Petter Mattei's "Love in the Time of Money" is...  positive

In [13]:
data.tail()

                                                  review sentiment
49995  I thought this movie did a down right good job...  positive
49996  Bad plot, bad dialogue, bad acting, idiotic di...  negative
49997  I am a Catholic taught in parochial elementary...  negative
49998  I'm going to have to disagree with the previou...  negative
49999  No one expects the Star Trek movies to be high...  negative

In [14]:
data.shape

(50000, 2)

In [15]:
data.sample(10)

                                                  review sentiment
46404  (SMALL SPOILERS) I just bought the DVD of this...  negative
39829  This is a spin off of Pulp Fiction. I thought ...  negative
49990  Lame, lame, lame!!! A 90-minute cringe-fest th...  negative
36268  I have not managed to completely block out thi...  positive
45448  This movie should have come with a disclaimer ...  negative
25303  Went with some friends and one of my friends m...  negative
32860  I swear if I did ever tried cocaine I'd be abl...  positive
22696  This movie has the feel of a college project o...  negative
22099  There are moments in this unique cartoon of pu...  negative
9349   I have just read what I believe to be an analy...  positive

In [17]:
data["review"]

0        One of the other reviewers has mentioned that ...
1        A wonderful little production. <br /><br />The...
2        I thought this was a wonderful way to spend ti...
3        Basically there's a family where a little boy ...
4        Petter Mattei's "Love in the Time of Money" is...
                               ...
49995    I thought this movie did a down right good job...
49996    Bad plot, bad dialogue, bad acting, idiotic di...
49997    I am a Catholic taught in parochial elementary...
49998    I'm going to have to disagree with the previou...
49999    No one expects the Star Trek movies to be high...
Name: review, Length: 50000, dtype: str

In [20]:
data["review"][0]

"One of the other reviewers has mentioned that after watching just 1 Oz episode you'll be hooked. They are right, as this is exactly what happened with me.<br /><br />The first thing that struck me about Oz was its brutality and unflinching scenes of violence, which set in right from the word GO. Trust me, this is not a show for the faint hearted or timid. This show pulls no punches with regards to drugs, sex or violence. Its is hardcore, in the classic use of the word.<br /><br />It is called OZ as that is the nickname given to the Oswald Maximum Security State Penitentary. It focuses mainly on Emerald City, an experimental section of the prison where all the cells have glass fronts and face inwards, so privacy is not high on the agenda. Em City is home to many..Aryans, Muslims, gangstas, Latinos, Christians, Italians, Irish and more....so scuffles, death stares, dodgy dealings and shady agreements are never far away.<br /><br />I would say the main appeal of the show is due to the fact that it goes where other shows wouldn't dare. Forget pretty pictures painted for mainstream audiences, forget charm, forget romance...OZ doesn't mess around. The first episode I ever saw struck me as so nasty it was surreal, I couldn't say I was ready for it, but as I watched more, I developed a taste for Oz, and got accustomed to the high levels of graphic violence. Not just violence, but injustice (crooked guards who'll be sold out for a nickel, inmates who'll kill on order and get away with it, well mannered, middle class inmates being turned into prison bitches due to their lack of street skills or prison experience) Watching Oz, you may become comfortable with what is uncomfortable viewing....thats if you can get in touch with your darker side."

1. tokenization
2. lowercase
3. uppercase
4. emojis
5. pancuations
6. html,url
7. stopwords
8. abbravation or slang
9.  steemming and lemmetization
10. spelling correction
11. whitspace

Lowercasing and Uppercasing

In [24]:
data["review"][3].upper()

"BASICALLY THERE'S A FAMILY WHERE A LITTLE BOY (JAKE) THINKS THERE'S A ZOMBIE IN HIS CLOSET & HIS PARENTS ARE FIGHTING ALL THE TIME.<BR /><BR />THIS MOVIE IS SLOWER THAN A SOAP OPERA... AND SUDDENLY, JAKE DECIDES TO BECOME RAMBO AND KILL THE ZOMBIE.<BR /><BR />OK, FIRST OF ALL WHEN YOU'RE GOING TO MAKE A FILM YOU MUST DECIDE IF ITS A THRILLER OR A DRAMA! AS A DRAMA THE MOVIE IS WATCHABLE. PARENTS ARE DIVORCING & ARGUING LIKE IN REAL LIFE. AND THEN WE HAVE JAKE WITH HIS CLOSET WHICH TOTALLY RUINS ALL THE FILM! I EXPECTED TO SEE A BOOGEYMAN SIMILAR MOVIE, AND INSTEAD I WATCHED A DRAMA WITH SOME MEANINGLESS THRILLER SPOTS.<BR /><BR />3 OUT OF 10 JUST FOR THE WELL PLAYING PARENTS & DESCENT DIALOGS. AS FOR THE SHOTS WITH JAKE: JUST IGNORE THEM."

In [25]:
data["review"][3].lower()

"basically there's a family where a little boy (jake) thinks there's a zombie in his closet & his parents are fighting all the time.<br /><br />this movie is slower than a soap opera... and suddenly, jake decides to become rambo and kill the zombie.<br /><br />ok, first of all when you're going to make a film you must decide if its a thriller or a drama! as a drama the movie is watchable. parents are divorcing & arguing like in real life. and then we have jake with his closet which totally ruins all the film! i expected to see a boogeyman similar movie, and instead i watched a drama with some meaningless thriller spots.<br /><br />3 out of 10 just for the well playing parents & descent dialogs. as for the shots with jake: just ignore them."

In [26]:
data["review"]=data["review"].str.upper()

In [27]:
data.head()

                                              review sentiment
0  ONE OF THE OTHER REVIEWERS HAS MENTIONED THAT ...  positive
1  A WONDERFUL LITTLE PRODUCTION. <BR /><BR />THE...  positive
2  I THOUGHT THIS WAS A WONDERFUL WAY TO SPEND TI...  positive
3  BASICALLY THERE'S A FAMILY WHERE A LITTLE BOY ...  negative
4  PETTER MATTEI'S "LOVE IN THE TIME OF MONEY" IS...  positive

In [28]:
data["review"]=data["review"].str.lower()

In [29]:
data["review"]

0        one of the other reviewers has mentioned that ...
1        a wonderful little production. <br /><br />the...
2        i thought this was a wonderful way to spend ti...
3        basically there's a family where a little boy ...
4        petter mattei's "love in the time of money" is...
                               ...
49995    i thought this movie did a down right good job...
49996    bad plot, bad dialogue, bad acting, idiotic di...
49997    i am a catholic taught in parochial elementary...
49998    i'm going to have to disagree with the previou...
49999    no one expects the star trek movies to be high...
Name: review, Length: 50000, dtype: str

In [30]:
type(data["review"])

pandas.Series

2.Tackle htmltags and url

In [35]:
text="""<!DOCTYPE html><html lang="en"><head><meta charset="UTF-8"><meta http-equiv="X-UA-Compatible" content="IE=edge"><meta name="viewport" content="width=device-width,
initial-scale=1.0"><title>Welcome to My
Website</title><style>body{font-family:'Arial',sans-serif;background-color
:#f0f0f0;color:#333;margin:20px}h1{color:#007bff}p{line-height:1.5}</style></head><body><header><h1>Welcome to My Awesome
Website!</h1></header><main><p>This is a sample HTML document created for
demonstration purposes.</p><p>Feel free to explore and enjoy the content
on this website.</p></main><footer><p>&copy; 2024 My Website. All rights
reserved.</p></footer></body></html>"""

In [40]:
import re

In [ ]:
def remove_html_tags(text):
    pattern=re.compile('<.*?>')
    return pattern.sub("",text)

In [42]:
remove_html_tags(text)

'<meta name="viewport" content="width=device-width,\ninitial-scale=1.0">Welcome to My\nWebsitebody{font-family:\'Arial\',sans-serif;background-color\n:#f0f0f0;color:#333;margin:20px}h1{color:#007bff}p{line-height:1.5}Welcome to My Awesome\nWebsite!This is a sample HTML document created for\ndemonstration purposes.Feel free to explore and enjoy the content\non this website.&copy; 2024 My Website. All rights\nreserved.'

In [44]:
data["review"]=data["review"].apply(remove_html_tags)

You can remove url using regex

In [45]:
 text2="checkout this link https://www.youtube.com/watch?v=VbNF9X1waSc&t=1s for more details    "

In [54]:
def remove_url(text2):
    pattern=re.compile('https?://\S+|www\.\S+')
    return pattern.sub("",text2)

<>:2: SyntaxWarning: invalid escape sequence '\S'
<>:2: SyntaxWarning: invalid escape sequence '\S'
C:\Users\Shraddha Chaudhari\AppData\Local\Temp\ipykernel_39156\3908321751.py:2: SyntaxWarning: invalid escape sequence '\S'
  pattern=re.compile('https?://\S+|www\.\S+')

In [55]:
remove_url(text2)

'checkout this link  for more details    '

we gonna handle punctuations

In [2]:
import string

In [3]:
string.punctuation

'!"#$%&\'()*+,-./:;<=>?@[\\]^_`{|}~'

In [4]:
exclude=string.punctuation

In [5]:
for char in exclude:
    print(char)

!
"
#
$
%
&
'
(
)
*
+
,
-
.
/
:
;
<
=
>
?
@
[
\
]
^
_
`
{
|
}
~

In [8]:
def remove_punc(text):
    for char in exclude:
        text=text.replace(char,"")
    return text

In [9]:
text="string @ *() with punctuation.!"

In [10]:
remove_punc(text)

'string   with punctuation'

In [11]:
text2="My name is ())(((Shraddha)) and I am a data scientist!!!"

In [12]:
remove_punc(text2)

'My name is Shraddha and I am a data scientist'

In [19]:
data["review"]=data["review"].apply(remove_punc)

In [20]:
data["review"]

0        One of the other reviewers has mentioned that ...
1        A wonderful little production br br The filmin...
2        I thought this was a wonderful way to spend ti...
3        Basically theres a family where a little boy J...
4        Petter Matteis Love in the Time of Money is a ...
                               ...
49995    I thought this movie did a down right good job...
49996    Bad plot bad dialogue bad acting idiotic direc...
49997    I am a Catholic taught in parochial elementary...
49998    Im going to have to disagree with the previous...
49999    No one expects the Star Trek movies to be high...
Name: review, Length: 50000, dtype: str

In [21]:
text1="FYI this is not true"
text2="LAMO the class was so funny"
text3="I want it ASAP"

In [22]:
chat_words={
"AFAIK":"As Far As I Know",
"AFK": "Away From Keyboard",
"ASAP":"As Soon As Possible",
"BTW":"By The Way",
"B4":"Before",
"LAMO":"Laugh My A.. Off",
"FYI":"For your information"    
}

In [23]:
chat_words["ASAP"]

'As Soon As Possible'

In [ ]:
# def chat_conversion(text):
#     new_text=[]
#     for word in text.split():
#         if word.upper() in chat_words:
#             new_text.append(chat_words[word.upper()])
#             print(new_text)
#             print(word.upper())
#         else:
#             new_text.append(word)
#     return " ".join(new_text)



def chat_conversion(text):
    new_text=[]
    for w in text.split():
        if w.upper() in chat_words:
            new_text.append(chat_words[w.upper()])
            print("IF: " + str(new_text))
        else:
            new_text.append(w)
            print("Else: " + str(new_text))
    return " ".join(new_text)


# chat_words[w.upper()]  -means chat_words["FYI"] → "For your information"

In [39]:
chat_conversion(text1)

IF: ['For your information']
Else: ['For your information', 'this']
Else: ['For your information', 'this', 'is']
Else: ['For your information', 'this', 'is', 'not']
Else: ['For your information', 'this', 'is', 'not', 'true']

'For your information this is not true'

Explanation of above code

🧠 Your Code Part
if word.upper() in chat_words:
    new_text.append(chat_words[word.upper()])
else:
    new_text.append(word)
🔍 Step-by-step understanding
👉 Step 1: Take one word

Example sentence:

FYI this is not true

Loop will take words one by one:

👉 First word = "FYI"

👉 Step 2: Convert to uppercase
word.upper()

👉 "FYI" → "FYI"
👉 "fyi" → "FYI"

✔ This helps match dictionary keys

👉 Step 3: Check in dictionary
if word.upper() in chat_words:

👉 Check:

"FYI" in chat_words

👉 YES ✅ (it exists)

👉 Step 4: Replace word
new_text.append(chat_words[word.upper()])

👉 Means:

chat_words["FYI"] → "For your information"

👉 So we store:

"For your information"
👉 Step 5: If NOT found

Example word:

"this"

Check:

"THIS" in chat_words

👉 NO ❌

So this runs:

else:
    new_text.append(word)

👉 Keep original word:

"this"
🧠 Final Flow
Word	In dictionary?	Output
FYI	Yes	For your information
this	No	this
is	No	is
🎯 Simple Meaning

👉 If word is shortcut → replace it
👉 If not → keep it same

💡 Very Simple Example
word = "FYI"

👉 Condition:

if "FYI" in chat_words:

✔ True → replace

word = "hello"

👉 Condition:

if "HELLO" in chat_words:

❌ False → keep same

🎯 One-line understanding

👉 “Check → Replace if found → Otherwise keep same”

🧠 Small Visual
FYI  → replace → For your information
this → keep → this
🚀 You are doing great 👍

This logic is used in:

text cleaning
preprocessing
NLP pipelines

👉 Next:
Do you want to:

Apply this to your review dataset
Move to Task 5 (sparse matrix analysis)

In [31]:
text1

'FYI this is not true'

In [40]:
chat_conversion(text2)

IF: ['Laugh My A.. Off']
Else: ['Laugh My A.. Off', 'the']
Else: ['Laugh My A.. Off', 'the', 'class']
Else: ['Laugh My A.. Off', 'the', 'class', 'was']
Else: ['Laugh My A.. Off', 'the', 'class', 'was', 'so']
Else: ['Laugh My A.. Off', 'the', 'class', 'was', 'so', 'funny']

'Laugh My A.. Off the class was so funny'

# Text Prepocessing

### NLTK
### TextBlob
### Spacy

#### this library have Huge funcationality

##### But we just gonna understand the basics and how to use it

In [4]:
text="this is my processing notebook pleae download this ntebook"

In [2]:
from textblob import TextBlob

In [5]:
textblob = TextBlob(text)

In [6]:
textblob.correct()

TextBlob("this is my processing notebook please download this notebook")

In [7]:
textblob.correct().string

'this is my processing notebook please download this notebook'

In [8]:
text2="here is my nme that is SUNNY SAVITA and he is good mntor"

In [9]:
textblob=TextBlob(text2)

In [12]:
textblob.correct().string

'here is my me that is SUNNY SAVITA and he is good motor'

In [13]:
text3="I'm brav ad stong prson"

In [15]:
textblob=TextBlob(text3)
textblob.correct().string

"I'm brave ad strong person"

In [17]:
import nltk
nltk.download("stopwords")

[nltk_data] Downloading package stopwords to C:\Users\Shraddha
[nltk_data]     Chaudhari\AppData\Roaming\nltk_data...
[nltk_data]   Package stopwords is already up-to-date!

True

In [19]:
from nltk.corpus import stopwords

In [20]:
stopwords.words("english")

['a',
 'about',
 'above',
 'after',
 'again',
 'against',
 'ain',
 'all',
 'am',
 'an',
 'and',
 'any',
 'are',
 'aren',
 "aren't",
 'as',
 'at',
 'be',
 'because',
 'been',
 'before',
 'being',
 'below',
 'between',
 'both',
 'but',
 'by',
 'can',
 'couldn',
 "couldn't",
 'd',
 'did',
 'didn',
 "didn't",
 'do',
 'does',
 'doesn',
 "doesn't",
 'doing',
 'don',
 "don't",
 'down',
 'during',
 'each',
 'few',
 'for',
 'from',
 'further',
 'had',
 'hadn',
 "hadn't",
 'has',
 'hasn',
 "hasn't",
 'have',
 'haven',
 "haven't",
 'having',
 'he',
 "he'd",
 "he'll",
 'her',
 'here',
 'hers',
 'herself',
 "he's",
 'him',
 'himself',
 'his',
 'how',
 'i',
 "i'd",
 'if',
 "i'll",
 "i'm",
 'in',
 'into',
 'is',
 'isn',
 "isn't",
 'it',
 "it'd",
 "it'll",
 "it's",
 'its',
 'itself',
 "i've",
 'just',
 'll',
 'm',
 'ma',
 'me',
 'mightn',
 "mightn't",
 'more',
 'most',
 'mustn',
 "mustn't",
 'my',
 'myself',
 'needn',
 "needn't",
 'no',
 'nor',
 'not',
 'now',
 'o',
 'of',
 'off',
 'on',
 'once',
 'only',
 'or',
 'other',
 'our',
 'ours',
 'ourselves',
 'out',
 'over',
 'own',
 're',
 's',
 'same',
 'shan',
 "shan't",
 'she',
 "she'd",
 "she'll",
 "she's",
 'should',
 'shouldn',
 "shouldn't",
 "should've",
 'so',
 'some',
 'such',
 't',
 'than',
 'that',
 "that'll",
 'the',
 'their',
 'theirs',
 'them',
 'themselves',
 'then',
 'there',
 'these',
 'they',
 "they'd",
 "they'll",
 "they're",
 "they've",
 'this',
 'those',
 'through',
 'to',
 'too',
 'under',
 'until',
 'up',
 've',
 'very',
 'was',
 'wasn',
 "wasn't",
 'we',
 "we'd",
 "we'll",
 "we're",
 'were',
 'weren',
 "weren't",
 "we've",
 'what',
 'when',
 'where',
 'which',
 'while',
 'who',
 'whom',
 'why',
 'will',
 'with',
 'won',
 "won't",
 'wouldn',
 "wouldn't",
 'y',
 'you',
 "you'd",
 "you'll",
 'your',
 "you're",
 'yours',
 'yourself',
 'yourselves',
 "you've"]

In [21]:
" sunny ".strip()

'sunny'

In [33]:
def remove_stop_words(text):
    new_text=[]
    for words in text.split():
        if words in stopwords.words("english"):
            new_text.append("")
            print("IF: " + str(new_text))
        else:
            new_text.append(words.strip())
            print("Else: " + str(new_text))
    return " ".join(new_text)

In [22]:
text="Hi i am sunny savita and i am working as a data sciensitst and genai engineer. now tell me who is sunny?"

In [34]:
remove_stop_words(text)

Else: ['Hi']
IF: ['Hi', '']
IF: ['Hi', '', '']
Else: ['Hi', '', '', 'sunny']
Else: ['Hi', '', '', 'sunny', 'savita']
IF: ['Hi', '', '', 'sunny', 'savita', '']
IF: ['Hi', '', '', 'sunny', 'savita', '', '']
IF: ['Hi', '', '', 'sunny', 'savita', '', '', '']
Else: ['Hi', '', '', 'sunny', 'savita', '', '', '', 'working']
IF: ['Hi', '', '', 'sunny', 'savita', '', '', '', 'working', '']
IF: ['Hi', '', '', 'sunny', 'savita', '', '', '', 'working', '', '']
Else: ['Hi', '', '', 'sunny', 'savita', '', '', '', 'working', '', '', 'data']
Else: ['Hi', '', '', 'sunny', 'savita', '', '', '', 'working', '', '', 'data', 'sciensitst']
IF: ['Hi', '', '', 'sunny', 'savita', '', '', '', 'working', '', '', 'data', 'sciensitst', '']
Else: ['Hi', '', '', 'sunny', 'savita', '', '', '', 'working', '', '', 'data', 'sciensitst', '', 'genai']
Else: ['Hi', '', '', 'sunny', 'savita', '', '', '', 'working', '', '', 'data', 'sciensitst', '', 'genai', 'engineer.']
IF: ['Hi', '', '', 'sunny', 'savita', '', '', '', 'working', '', '', 'data', 'sciensitst', '', 'genai', 'engineer.', '']
Else: ['Hi', '', '', 'sunny', 'savita', '', '', '', 'working', '', '', 'data', 'sciensitst', '', 'genai', 'engineer.', '', 'tell']
IF: ['Hi', '', '', 'sunny', 'savita', '', '', '', 'working', '', '', 'data', 'sciensitst', '', 'genai', 'engineer.', '', 'tell', '']
IF: ['Hi', '', '', 'sunny', 'savita', '', '', '', 'working', '', '', 'data', 'sciensitst', '', 'genai', 'engineer.', '', 'tell', '', '']
IF: ['Hi', '', '', 'sunny', 'savita', '', '', '', 'working', '', '', 'data', 'sciensitst', '', 'genai', 'engineer.', '', 'tell', '', '', '']
Else: ['Hi', '', '', 'sunny', 'savita', '', '', '', 'working', '', '', 'data', 'sciensitst', '', 'genai', 'engineer.', '', 'tell', '', '', '', 'sunny?']

'Hi   sunny savita    working   data sciensitst  genai engineer.  tell    sunny?'

🔴 Step-by-step Explanation
✔️ 1. Function definition
def remove_stop_words(text):

👉 You are creating a function
👉 It takes text (sentence) as input

✔️ 2. Empty list
new_text = []

👉 This will store the final cleaned words

✔️ 3. Loop through each word
for words in text.split():

👉 .split() breaks sentence into words

Example:

"Hi i am sunny"
→ ["Hi", "i", "am", "sunny"]
✔️ 4. Check stopwords
if words in stopwords.words("english"):

👉 Stopwords = common words
Examples:

I, am, is, the, and, etc.

👉 These words are usually removed in NLP

✔️ 5. If it is a stopword
new_text.append("")

👉 You are adding empty string (basically removing word)

✔️ 6. If NOT stopword
new_text.append(words.strip())

👉 Keep the word
👉 .strip() removes extra spaces

✔️ 7. Join words back
" ".join(new_text)

👉 Converts list → sentence

✔️ 8. Remove extra spaces
.replace("  "," ")

👉 Because you added "", extra spaces come
👉 This fixes double spaces

🔴 Example Output

Input:

text="Hi i am sunny savita and i am working as a data sciensitst"

Output (approx):

"Hi sunny savita working data sciensitst"

👉 Removed:

i, am, and, as, a
⚠️ Small Problems in Your Code
❌ Problem 1: Inefficient
stopwords.words("english")

👉 This runs again and again inside loop (slow)

✅ Better version
from nltk.corpus import stopwords

def remove_stop_words(text):
    stop_words = set(stopwords.words("english"))
    new_text = []
    
    for word in text.split():
        if word.lower() not in stop_words:
            new_text.append(word)
    
    return " ".join(new_text)
🔥 Improvements

✔ Use set() → faster
✔ Use word.lower() → handles "I", "i"
✔ No need for "" and replace

🧠 Simple Understanding

👉 Your code is doing:

"Remove common useless words from sentence"

💬 English Correction

You wrote:
❌ "EXPLAIN THIS CODE TOO"
✅ Better:
👉 "Please explain this code too."

🗣 Practice sentence

👉 "This function removes stopwords from a sentence."

If you want, next I can show:
👉 
how to remove punctuation
👉 
how to do stemming/lemmatization

(very important for NLP 🚀)